---
title: "Mise en forme des données et premières visualisations"
output: html_document
---

```{r}
# # prepare 2021 data set with all arrondissement
# # only launch once
# setwd("~/Documents/repositories/immobilier-paris/data/2021/")
# for (data in list.files()){
#   
#   # Create the first data if no data exist yet
#   if (!exists("dataset")){
#     dataset <- read.csv(data, header=TRUE)
#   }
#   
#   # if data already exist, then append it together
#   if (exists("dataset")){
#     tempory <-read.csv(data, header=TRUE)
#     dataset <-unique(rbind(dataset, tempory))
#     rm(tempory)
#   }
# }
# View(dataset)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(ggplot2)
library(dplyr)
library(lubridate)
library(stringr) # str_split
library(ggridges)
```


```{r}
# lecture des données
df_2016 <- read.csv("./data/2016.csv")
df_2017 <- read.csv("./data/2017.csv")
df_2018 <- read.csv("./data/2018.csv")
df_2019 <- read.csv("./data/2019.csv")
df_2020 <- read.csv("./data/2020.csv")
df_2021 <- read.csv("./data/2021.csv")
df_2022 <- read.csv("./data/2022.csv")

# handle something strange in 2021
df_2021 <- df_2021[, 2:41]

df <- rbind(df_2016, df_2017, df_2018, df_2019, df_2020, df_2021, df_2022)

# on ne garde que les codes postaux de Paris
print(df)
df <- df[df$code_postal %in% c( paste0("7500",1:9),paste0("750",10:20)) ,]
print(df)

useful_columns <- c("date_mutation", 
                    "valeur_fonciere", 
                    "nature_mutation", 
                    "code_postal", 
                    "nombre_pieces_principales", 
                    #"surface_reelle_bati", 
                    "lot1_surface_carrez", 
                    "type_local", 
                    "nom_commune",
                    "lot2_surface_carrez",
                    "adresse_numero",
                    "adresse_nom_voie")

df <- df[, useful_columns]

df$annee <- year(df$date_mutation)
```


```{r}
# # integrate 2022 semester 1 - there was a change in the format so the treatment is different than previous years
# df_2022 <- read.table("./data/valeursfoncieres-2022-s1.txt", sep = "|", dec = ",", blank.lines.skip = T, fill = T, header = T)
# 
# # extract only Paris
# df_2022 <- df_2022[df_2022$Code.postal %in% c( paste0("7500",0:9), paste0("750",10:20)),]
# 
# # change date so that it matches other documents
# df_2022$date_mutation <- dmy(df_2022$Date.mutation)
# 
# df_2022 <- df_2022[, c("date_mutation", "Valeur.fonciere", "Nature.mutation", "Code.postal", "Nombre.pieces.principales", "Surface.Carrez.du.1er.lot", "Type.local", "Commune", "Surface.Carrez.du.2eme.lot", "No.voie", "Voie")]
# 
# colnames(df_2022) <- useful_columns
# 
# df_2022$annee <- year(df_2022$date_mutation)
# 
# 
# # df_2022$valeur_fonciere <- str_split(df_2022$valeur_fonciere, ",", n = 2, simplify = FALSE)
# # 
# # # should be improved
# # for (i in 1:nrow(df_2022)){
# #   df_2022$valeur_fonciere[i] <- df_2022$valeur_fonciere[i][[1]][1]
# # }
# 
# df_2022$valeur_fonciere <- as.numeric(df_2022$valeur_fonciere)
# 
# df_2022$lot1_surface_carrez  <- sub(",", ".", df_2022$lot1_surface_carrez, fixed = T)
# df_2022$lot1_surface_carrez <- as.numeric(df_2022$lot1_surface_carrez)
# 
# df_2022$lot2_surface_carrez  <- sub(",", ".", df_2022$lot2_surface_carrez, fixed = T)
# df_2022$lot2_surface_carrez <- as.numeric(df_2022$lot2_surface_carrez)
# df <- rbind(df, df_2022)
```


```{r}
rm(df_2016, df_2017, df_2018, df_2019, df_2020, df_2021, df_2022)
```


```{r}
# garde uniquement les ventes avec des m2 annoncés
nrow(df)
df <- df[!is.na(df$lot1_surface_carrez),]
nrow(df)

# filtre les lignes non uniques
nrow(df)
df <- unique(df)
nrow(df)

#  années comme facteur
df$annee <- as.factor(df$annee)
```


```{r}
# on ne garde que les ventes, et les biens de type habitation
print(nrow(df))

print("On ne garde que les apparts et les maisons")
df <- df[df$type_local %in% c("Appartement", "Maison"),]
print(nrow(df))

print("On ne garde que les ventes")
df <- df[df$nature_mutation == "Vente",]
print(nrow(df))

print("On garde les observations pour lesquelles on a un prix de vente")
df <- df[!is.na(df$valeur_fonciere),]
print(nrow(df))
```


```{r}
table(df$annee)
```



```{r}
summary(df)
```



```{r}
df$m2 <- case_when(00 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 20 ~ "0-20",
                  20 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 25 ~ "20-25",
                  25 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 30 ~ "25-30",
                  30 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 35 ~ "30-35",
                  35 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 40 ~ "35-40",
                  40 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 45 ~ "40-45",
                  45 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 50 ~ "45-50",
                  50 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 55 ~ "50-55",
                  55 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 60 ~ "55-60",
                  60 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 65 ~ "60-65",
                  65 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 70 ~ "65-70",
                  70 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 75 ~ "70-75",
                  75 <= df$lot1_surface_carrez & df$lot1_surface_carrez < 80 ~ "75-80",
                  80 <= df$lot1_surface_carrez  ~ "80+")

df$prix.m2 <- df$valeur_fonciere / df$lot1_surface_carrez
```


```{r}
df[df$m2 != "0-10" & df$prix.m2 < 30000,] %>%
  group_by(m2, annee) %>%
  summarise_at(vars(prix.m2), list(name = mean)) %>%
    ggplot(aes(x = m2, y = name, group = annee, color = annee)) +
      geom_line() +
      theme_classic() +
  ylab("Prix au m2") +
  xlab("Surface du premier lot (considéré comme le lot principal)")

```


```{r}
ggplot(df[df$prix.m2 < 20000,], aes(x = prix.m2, group = annee, fill = annee)) +
  geom_density(alpha = 0.7, size = 0.8) +
  theme_classic()
```

```{r}
ggplot(df[df$prix.m2 < 20000 & df$prix.m2 > 2000,], aes(x = prix.m2, y = annee, fill = annee)) +
  geom_density_ridges(alpha = 0.8) +
  #geom_histogram() +
  theme_minimal() +
  xlab("Prix au m2") +
  ylab("") + 
  theme(legend.position = "none", text = element_text(size = 10, face = "bold"), axis.text.y = element_text(size = 10), axis.text.x = element_text(size = 17))

```


```{r}
ggplot(df[df$lot1_surface_carrez < 150 & df$m2 != "0-10" & df$prix.m2 < 30000 & df$prix.m2 > 3000,], aes(x = lot1_surface_carrez, y = prix.m2, color = annee, group = annee)) +
  #geom_point(alpha = 0.1) +
  geom_smooth(aes(fill = annee)) +
  theme_minimal() +
  xlim(10, 150) +
  ylab("Prix au mètre carré (euros)") +
  xlab("Surface du premier lot (considéré comme le lot principal)") +
  theme(legend.position="bottom") 
# +
#   ggtitle("Évolution du marché immobilier parisien")
ggsave("./prix_annee.jpg")
```


```{r}
df$location <- case_when(df$code_postal %in% c("75010", "75018", "75019", "75020", "75011") ~ "Nord & Nord-Est",
                         df$code_postal %in% c("75001", "75002", "75003", "75004", "75005", "75006", "75007", "75016", "75017", "75008", "75009") ~ "Centre & Ouest",
                         df$code_postal %in% c("75013", "75014", "75012","75015") ~ "Sud & Sud-Est")
```

```{r}
ggplot(df[df$lot1_surface_carrez < 150 & df$m2 != "0-10" & df$prix.m2 < 40000 & df$prix.m2 > 3000,], aes(x = lot1_surface_carrez, y = prix.m2, color = annee, group = annee)) +
  #geom_point(alpha = 0.1) +
  geom_smooth(aes(fill = annee)) +
  theme_minimal()  +
  xlim(10, 150) +
  ylab("Prix au mètre carré (euros)") +
  xlab("Surface du premier lot (considéré comme le lot principal)") +
  theme(legend.position="bottom") +
  facet_grid(~location)

ggsave("./prix_annee_localisation.jpg")
```


```{r}
ggplot(df[df$prix.m2 < 20000,], aes(x = prix.m2, y = annee, fill = annee)) +
  geom_density_ridges(alpha = 0.8) +
  #geom_histogram() +
  theme_minimal() +
  xlab("Prix au m2") +
  ylab("") + 
  facet_grid(~location) +
  theme(legend.position = "none", text = element_text(size = 10, face = "bold"), axis.text.y = element_text(size = 10), axis.text.x = element_text(size = 17))
```


```{r}
ggplot(df[df$lot1_surface_carrez < 150 & df$m2 != "0-10" & df$prix.m2 < 40000 & df$prix.m2 > 3000 & df$code_postal %in% c("75010", "75018", "75019", "75020"),], aes(x = lot1_surface_carrez, y = prix.m2, color = annee, group = annee)) +
  #geom_point(alpha = 0.1) +
  geom_smooth(aes(fill = annee)) +
  theme_minimal() +
  ylab("Prix au mètre carré (euros)") +
  xlab("Surface du premier lot (considéré comme le lot principal)") +
  theme(legend.position="bottom") +
  ggtitle("Évolution du marché immobilier parisien (nord et nord est)")


ggplot(df[df$lot1_surface_carrez < 150 & df$m2 != "0-10" & df$prix.m2 < 40000 & df$prix.m2 > 3000 & df$code_postal %in% c("75001", "75002", "75003", "75004", "75006", "75007"),], aes(x = lot1_surface_carrez, y = prix.m2, color = annee, group = annee)) +
  #geom_point(alpha = 0.1) +
  geom_smooth(aes(fill = annee)) +
  theme_minimal() +
  ylab("Prix au mètre carré (euros)") +
  xlab("Surface du premier lot (considéré comme le lot principal)") +
  theme(legend.position="bottom") +
  ggtitle("Évolution du marché immobilier parisien (centre et ouest)")
```


Outliers ?

```{r}
df$outliers <- ifelse(df$prix.m2 < 3000, "prix très bas", "RAS")

ggplot(df[!is.na(df$lot1_surface_carrez) & df$lot1_surface_carrez < 150 & df$m2 != "0-10" & df$prix.m2 < 30000,], aes(x = lot1_surface_carrez, y = prix.m2, color = outliers)) +
  geom_point(alpha = 0.3) +
  theme_minimal() +
  ylab("Prix au mètre carré (euros)") +
  xlab("Surface du premier lot (considéré comme le lot principal)") +
  theme(legend.position="bottom")
```


```{r}
#df$code_postal <- as.factor(df$code_postal)
df[df$m2 != "0-10" & df$prix.m2 < 20000 & df$prix.m2 > 3000,] %>%
  group_by(annee) %>%
  summarise_at(vars(prix.m2), list(name = mean, sd = sd)) %>%
    ggplot(aes(x = annee, y = name)) +
      geom_point() +
  geom_errorbar(aes(ymin=name - sd, ymax = name + sd), width=.2,position=position_dodge(0.05)) +
      theme_minimal() +
  ylim(5000, 15000) +
  ylab("Prix moyen au m2 et écart type") +
  xlab("Prix moyen")
```


```{r}
df.resume <- df[df$m2 != "0-10" & df$prix.m2 < 30000,] %>%
  group_by(code_postal, annee) %>%
  summarise(prix.median = median(prix.m2))
```

```{r}
df.resume[df.resume$annee == 2021,]
```



```{r}
df[!is.na(df$m2) & df$m2 != "0-10" & df$prix.m2 < 35000,] %>%
  group_by(annee) %>%
  summarise(n = n()) %>%
  ggplot(aes(x = annee, y = n)) +
      #geom_point() +
      geom_bar(stat="identity", fill = "pink", color = "darkblue", alpa = 0.5) +
      theme_bw() +
  ylim(0,40000) +
  ylab("Nombre de transactions immobilières") +
  xlab("Année") 
ggsave("./nombre_transac.jpg")
```

```{r}
restricted.set <- df[df$prix.m2 < 35000,]
test <- as.data.frame(aggregate(restricted.set$valeur_fonciere, by=list(Category=restricted.set$annee), FUN=sum))
ggplot(test, aes(x = Category, y = x)) +
      #geom_point() +
      geom_bar(stat="identity", fill = "pink", color = "darkblue", alpa = 0.5) +
      theme_classic() +
  ylab("Total en euros des transactions annuelles") +
  xlab("Année")
```

```{r}
df[!is.na(df$m2) & df$prix.m2 < 20000 & df$prix.m2 > 5000 & df$m2 != "80+",] %>%
  group_by(m2, annee) %>%
  summarise(n = n()) %>%
  ggplot(aes(x = m2, y = n, color = annee, group = annee)) +
      geom_point() +
      geom_line() +
      theme_classic() +
  ylab("Nombre de transactions immobilières de type habitation")
```

